#pragma once
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_MESSANGERCLIENT_DIALOG		102
#define IDC_REGISTRATION_BUTTON	        103
#define IDC_LOG_IN_BUTTON               104
#define IDD_AUTHENTIFICATION_DIALOG     105
#define IDC_PASSWORD_EDIT				106
#define IDC_LOGIN_EDIT					107


#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
